project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "files/"    
  output-dir: docs
  

execute:
  freeze: auto  # Re-render only when source changes: Taken from Andrew Heiss yml
  
website:
  title: "Programming for Education"
  description: "Intro to Programming for PhD in Education at Harvard University"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: "R Tutorials"
        file: content/01-basics.qmd
      - text: "Stata tutorials"
        file: content/01-basics-stata.qmd
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/RRMaximiliano/edu-harvard-intro-to-R
            
  favicon: "/files/img/Harvard-Logo.png"
  
  
  page-footer:
    left: |
      Original content {{< fa brands creative-commons >}} by [{{< var attribution.name_no_title >}}]({{< var attribution.url >}}) <br>
      Additional content {{< fa brands creative-commons >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      This website was built with {{< fa brands r-project >}} and <a href="https://quarto.org/">Quarto</a>.<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

  sidebar:
    - title: "R Content"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Content"
          contents:
          - text: "1: Intro to R"
            file: content/01-basics.qmd
          - text: "2: Data cleaning"
            file: content/02-data-cleaning.qmd
          - text: "3: Data wrangling"
            file: content/03-data-wrangling.qmd
          - text: "4: Data analysis"
            file: content/04-data-analysis.qmd  
          - text: "5: Building Summary Statistics Tables"
            file: content/05-data-summ.qmd               
          - text: "6: Data Visualization"
            file: content/06-data-viz.qmd
          - text: "7: Regular Expressions"
            file: content/07-regex.qmd 

    - title: "Stata Content"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Content"
          contents:
          - text: "1: Intro to Stata"
            file: content/01-basics-stata.qmd
            
format:
  html:
    theme:
      - cosmo
      - html/custom.scss
    toc: true
