project:
  type: website
  output-dir: docs

website:
  title: "R for Education"
  description: "Intro to R for PhD in Education at Harvard University"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: "Tutorials"
        file: content/01-basics.qmd
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/RRMaximiliano/edu-harvard-intro-to-R
            
  favicon: "/files/img/Harvard-Logo.png"

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Content"
          contents:
          - text: "1: Intro to R"
            file: content/01-basics.qmd
          - text: "2: Data cleaning -- Part 1"
            file: content/02-data-cleaning.qmd
          - text: "3: Data cleaning -- Part 2"
            file: content/03-data-cleaning-part-ii.qmd
          - text: "4: Regular Expressions"
            file: content/04-regex.qmd    
    
format:
  html:
    theme:
      - cosmo
      - html/custom.scss
    toc: true
