project:
  type: website
  output-dir: docs

website:
  title: "PhD in Education, Harvard University: Intro to R"
  description: "Intro to R for PhD in Education at Harvard University"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: "Intro to R"
        file: content/01-basics.qmd
        file: content/02-data-cleaning.qmd

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Content"
          contents:
          - text: "1: Intro to R"
            file: content/01-basics.qmd
          - text: "2: Data cleaning -- Part 1"
            file: content/02-data-cleaning.qmd
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

page-footer:
  left: |
    Content {{< fa brands creative-commons >}} {{< var copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
    All content licensed under a {{< fa brands creative-commons >}}
    {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
    [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
  right: |
    Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
    [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})