project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "files/"    
  output-dir: docs
  

execute:
  freeze: auto  # Re-render only when source changes: Taken from Andrew Heiss yml
  
website:
  title: "R for Education"
  description: "Intro to R for PhD in Education at Harvard University"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: "Tutorials"
        file: content/01-basics.qmd
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/RRMaximiliano/edu-harvard-intro-to-R
            
  favicon: "/files/img/Harvard-Logo.png"
  
  page-footer:
    right: |
      This website was built with <a href="https://quarto.org/">Quarto</a>.

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Content"
          contents:
          - text: "1: Intro to R"
            file: content/01-basics.qmd
          - text: "2: Data cleaning -- Part 1"
            file: content/02-data-cleaning.qmd
          - text: "3: Data cleaning -- Part 2"
            file: content/03-data-cleaning-part-ii.qmd
          - text: "4: Regular Expressions"
            file: content/04-regex.qmd
          - text: "5: Data visualization"
            file: content/05-data-viz.qmd

format:
  html:
    theme:
      - cosmo
      - html/custom.scss
    toc: true
